os: linux
dist: xenial
language: python
python:
  - "3.8"
services:
  - xvfb

install: pip install flake8 numpy opencv-python
  
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - python eyeloop.py --video 'examples/optokinetic-reflex/Wild-type.avi'
